kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend-deployment
  namespace: mystore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mystore-app
  template:
    metadata:
      name: backend-pod
      namespace: mystore
      labels:
        app: mystore-app
    spec:
      containers:
      - name: mystore-app-container
        image: sahilmandal/mystore-mainapp:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/mydb
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-user
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
